### ISSUE TITLE
How can I add image to excel sheet?

### ISSUE THREAD

**Issue by daicaga** [JanX2/JXLS#16]
Dear @JanX2 

I used your library for my application. Thanks you for your lib!

I have a chart in my report, I convert it to image but I don't know how can I put it in the sheet.
Please help me!

Regards,
Ga

**Comment by JanX2** [comment]
Sorry @daicaga. You will have to add that functionality yourself by forking https://github.com/JanX2/xlslib and adding it to the JXLS wrapper.
