### ISSUE TITLE
How can I merge cells?

### ISSUE THREAD

**Issue by jcabreram** [JanX2/JXLS#17]
Hello Jan!

Thanks for your great library! I would like to merge two empty cells at the top of the spreadsheet for the title, but I can't seem to find how to do that.

I found the -(void)mergeCellsInRect:(JXLSRECT)range method in JXLSWorkSheet.h but what does the (JXLSRECT)range object refer to?

Can you please help me figure out how to do this? Thanks!

**Comment by JanX2** [comment]
@jcabreram You can Command-click on such symbols in Xcode to trace back to their definitions. This is just a CG/NSRect currently. You can have a look at the implementation of the method in the ame way to figure out what it does internally. Basically it just converts the geometric properties of the rect into integers and passes those to the wrapped C++ method to merge the cells.
