### ISSUE TITLE
"Pods-environment.h" not found with CocoaPods 0.34.1

### ISSUE THREAD

**Issue by mschm** [JanX2/JXLS#8]
This issue applies to CocoaPods 0.34.1 and above installations.

Building JXLS fails because the file _Pods-environment.h_ (import in JXLS.h) has moved to _../Target Support Files/Pods/_
See the CocoaPods changelog at http://blog.cocoapods.org/CocoaPods-0.34

To fix this issue and stay compatible with older CocoaPods installations I suggest to make use of the ___has_include_ macro as discussed here: https://github.com/CocoaPods/CocoaPods/issues/2536

**Comment by kts** [comment]
I am still getting this error.  Is there an example of how to fix this with __has_include?

**Comment by kts** [comment]
After further inspection, it looks like this isn't really needed. If anyone else sees this same problem - it looks safe to just remove the #ifdef COCOAPODS block in JXLS.h - it's only needed for the #if block below.

**Comment by JasmeetDev** [comment]
Has anyone resolved this issue
Any help?
